### ISSUE TITLE
contained packages?

### ISSUE THREAD

**Issue by mircealungu** [Perlten/MT-diagrams#15]
Initially because there were multiple "test_something" packages visible I thought I could add a regex there, e.g. "test*". however, that didn't work. so i added "test". and the others disappeared. this was good news for me, because the view was simpler. 

at the same time, I wonder if we might be confusing people a bit this way? 

shouldn't the fact that there is a hierarchy between packages be taken into account somehow? two ways in which i could envision doing this are: 

1. in good old Softwarenaut, i would only show the top level package (e.g. test) and it's contents only if the user explicitly wanted to expand that package. 

2. alternative would be showing containment of packages (I think the framework can do packages inside of other packages - something about them having the . in their name you mentioned?) so `test_data` would be shown inside the "test" package.

**Comment by JesperRusbjerg** [comment]
We have considered these options, and we might try them and see what works best

We're gonna try to add a new feature to the ignorePackages, where you can either add "test" to remove the folder "test", and if you want to remove any package containing test in its path, you add "test*" to ignorePackages, that change will be coming up during this weeks iteration

as for the embedded packages, we believe the view will be rather hard to understand, due to many arrows entering the same boxes, but we're open to trying it

lastly, we're gonna try to add a view where the package paths are present, instead of the package names, in order to make it easier to see where the package is located in the system

Gonna post updates in this issue as we implement new features in regards to this

**Comment by mircealungu** [comment]
> as for the embedded packages, we believe the view will be rather hard to understand, due to many arrows entering the same boxes, but we're open to trying it
- let's test it quickly. but i agree with you that it might end up being too complicated. i wonder if the best approach would be to allow one to specify the number of sub-levels a package should be opened into? there could be two of these package-depth configuration:
- global-depth -- how much does one want to expand all the packages by default
- specific-depths -- as the name says, allow various packages to be configured

I could envision something like:
- global-depth: 2
- specific-depths: [{test:1}, {api:1}]

do you see what I mean?

**Comment by JesperRusbjerg** [comment]
In a new push coming tomorrow, there is new ways of filtering, with *, specific package and package name
and a path-naming-view instead of package-naming in the diagram, which i currently think might a new best-way to go, as it just gives a more clear view of where each package in the diagram belongs
the new push has also fixed the bugs you encountered, except for the missing dependency which we still need to look into

We will send you a message on teams when the new version is live, and you can update the package to test it

Super good feedback by the way!!

As for the "global-depth" - this is something which we have discussed, and something which is very much implementable in our current system. But, I think it needs to be explored a little more: What is the difference between global-depth and specific depth? does it mean that if global depth is 2, the top 2 layers are in the diagram? and then you need to select packages from the 1st-2nd layer to further expand those?

What happens if "global-depth 2" is selected, but you choose to pick a specfic depth on a package which starts at layer 5? should that still be in the diagram then? or should the global-depth overrule and not show deeper packages?

Have you tried the "packages" input yet? You can specify which parts of the system you want to see by giving in a path(or multiple), does that not kind of solve the same thing, as you are able to select which parts of the system you want to see?

I think maybe a combination of "specific-depths" and "package" is better than global depths? So when giving a "package" you want to see, you can give it a "specific depth" too -
Then you could specify, "I want to see the api section with depth 2", and i want to see how that relates to "core/model depth 3"? I think this gives more flexibility and precise views than the "global"/"taking it from the top of the diagram", what do you think?

**Comment by mircealungu** [comment]
> I think maybe a combination of "specific-depths" and "package" is better than global depths? So when giving a "package" you want to see, you can give it a "specific depth" too -
Then you could specify, "I want to see the api section with depth 2", and i want to see how that relates to "core/model depth 3"? I think this gives more flexibility and precise views than the "global"/"taking it from the top of the diagram", what do you think?

this could be cool! if i can do that, that should be fine i think. once you have this implemented let me know please; i'd like to try it again on my test case!
